spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_user
    username: root

jpa:
  show-sql: true


flyway:
  locations: db.migration


server:
  port: 8082